import {ActionType as CoreActionType} from "envkey-client-core/dist/types"

export const ActionType = {
  ...CoreActionType,

  DISCONNECTED: "envkey/DISCONNECTED",

  REACTIVATED_BRIEF: "envkey/REACTIVATED_BRIEF",
  REACTIVATED_LONG: "envkey/REACTIVATED_LONG",

  APP_LOADED: "envkey/APP_LOADED",

  SELECTED_OBJECT: "envkey/SELECTED_OBJECT",

  CLOSE_GENERATED_INVITE_LINK: "envkey/CLOSE_GENERATED_INVITE_LINK",

  EXPORT_ENVIRONMENT: "envkey/EXPORT_ENVIRONMENT",

  START_DEMO: "envkey/START_DEMO",
  SET_DEMO_DOWNLOAD_URL: "envkey/SET_DEMO_DOWNLOAD_URL",
  GENERATE_DEMO_ORG_REQUEST: "envkey/GENERATE_DEMO_ORG_REQUEST",
  GENERATE_DEMO_ORG_SUCCESS: "envkey/GENERATE_DEMO_ORG_SUCCESS",
  GENERATE_DEMO_ORG_FAILED: "envkey/GENERATE_DEMO_ORG_FAILED",

  SOCKET_SUBSCRIBE_ORG_CHANNEL: "envkey/SOCKET_SUBSCRIBE_ORG_CHANNEL",
  SOCKET_SUBSCRIBE_OBJECT_CHANNEL: "envkey/SOCKET_SUBSCRIBE_OBJECT_CHANNEL",
  SOCKET_UNSUBSCRIBE_OBJECT_CHANNEL: "envkey/SOCKET_UNSUBSCRIBE_OBJECT_CHANNEL",
  SOCKET_USER_UNSUBSCRIBED_ORG_CHANNEL: "envkey/SOCKET_USER_UNSUBSCRIBED_ORG_CHANNEL",
  SOCKET_USER_UNSUBSCRIBED_OBJECT_CHANNEL: "envkey/SOCKET_USER_UNSUBSCRIBED_OBJECT_CHANNEL",
  SOCKET_USER_SUBSCRIBED_ORG_CHANNEL: "envkey/SOCKET_USER_SUBSCRIBED_ORG_CHANNEL",
  SOCKET_USER_SUBSCRIBED_OBJECT_CHANNEL: "envkey/SOCKET_USER_SUBSCRIBED_OBJECT_CHANNEL",
  SOCKET_UPDATE_ENVS_STATUS: "envkey/SOCKET_UPDATE_ENVS_STATUS",
  PROCESSED_SOCKET_UPDATE_ENVS_STATUS: "envkey/PROCESSED_SOCKET_UPDATE_ENVS_STATUS",
  SOCKET_UPDATE_LOCAL_STATUS: "envkey/SOCKET_UPDATE_LOCAL_STATUS",
  SOCKET_BROADCAST_ENVS_STATUS: "envkey/SOCKET_BROADCAST_ENVS_STATUS",
  SOCKET_UNSUBSCRIBE_ALL: "envkey/SOCKET_UNSUBSCRIBE_ALL",
  SOCKET_ORG_UPDATE: "envkey/SOCKET_ORG_UPDATE",

  BILLING_UPGRADE_SUBSCRIPTION: "envkey/BILLING_UPGRADE_SUBSCRIPTION",
  BILLING_CANCEL_SUBSCRIPTION: "envkey/BILLING_CANCEL_SUBSCRIPTION",
  BILLING_UPDATE_CARD: "envkey/BILLING_UPDATE_CARD",
  BILLING_OPEN_STRIPE_FORM: "envkey/BILLING_OPEN_STRIPE_FORM",
  BILLING_STRIPE_FORM_SUBMITTED: "envkey/BILLING_STRIPE_FORM_SUBMITTED",
  BILLING_STRIPE_FORM_CLOSED: "envkey/BILLING_STRIPE_FORM_CLOSED",
  BILLING_UPDATE_CARD_REQUEST: "envkey/BILLING_UPDATE_CARD_REQUEST",
  BILLING_UPDATE_CARD_SUCCESS: "envkey/BILLING_UPDATE_CARD_SUCCESS",
  BILLING_UPDATE_CARD_FAILED: "envkey/BILLING_UPDATE_CARD_FAILED",
  BILLING_UPDATE_SUBSCRIPTION_REQUEST: "envkey/BILLING_UPDATE_SUBSCRIPTION_REQUEST",
  BILLING_UPDATE_SUBSCRIPTION_SUCCESS: "envkey/BILLING_UPDATE_SUBSCRIPTION_SUCCESS",
  BILLING_UPDATE_SUBSCRIPTION_FAILED: "envkey/BILLING_UPDATE_SUBSCRIPTION_FAILED",

  BILLING_FETCH_INVOICE_LIST_REQUEST: "envkey/BILLING_FETCH_INVOICE_LIST_REQUEST",
  BILLING_FETCH_INVOICE_LIST_SUCCESS: "envkey/BILLING_FETCH_INVOICE_LIST_SUCCESS",
  BILLING_FETCH_INVOICE_LIST_FAILED: "envkey/BILLING_FETCH_INVOICE_LIST_FAILED",

  BILLING_FETCH_INVOICE_PDF: "envkey/BILLING_FETCH_INVOICE_PDF",
  BILLING_FETCH_INVOICE_PDF_REQUEST: "envkey/BILLING_FETCH_INVOICE_PDF_REQUEST",
  BILLING_FETCH_INVOICE_PDF_SUCCESS: "envkey/BILLING_FETCH_INVOICE_PDF_SUCCESS",
  BILLING_FETCH_INVOICE_PDF_FAILED: "envkey/BILLING_FETCH_INVOICE_PDF_FAILED",
  BILLING_SAVE_INVOICE_PDF_SUCCESS: "envkey/BILLING_SAVE_INVOICE_PDF_SUCCESS",
  BILLING_SAVE_INVOICE_PDF_FAILED: "envkey/BILLING_SAVE_INVOICE_PDF_FAILED",

  UPDATE_VERSION_FILTERS: "envkey/UPDATE_VERSION_FILTERS"
}