export const
  DISCONNECTED = "envkey/DISCONNECTED",

  REACTIVATED_BRIEF = "envkey/REACTIVATED_BRIEF",
  REACTIVATED_LONG = "envkey/REACTIVATED_LONG",

  RESET_VERIFY_EMAIL = "envkey/RESET_VERIFY_EMAIL",

  APP_LOADED = "envkey/APP_LOADED",

  RESET_ACCEPT_INVITE = "envkey/RESET_ACCEPT_INVITE",

  SELECTED_OBJECT = "envkey/SELECTED_OBJECT",

  CLOSE_GENERATED_INVITE_LINK = "envkey/CLOSE_GENERATED_INVITE_LINK",

  EXPORT_ENVIRONMENT = "envkey/EXPORT_ENVIRONMENT",

  START_DEMO = "envkey/START_DEMO",
  SET_DEMO_DOWNLOAD_URL = "envkey/SET_DEMO_DOWNLOAD_URL",
  GENERATE_DEMO_ORG_REQUEST = "envkey/GENERATE_DEMO_ORG_REQUEST",
  GENERATE_DEMO_ORG_SUCCESS = "envkey/GENERATE_DEMO_ORG_SUCCESS",
  GENERATE_DEMO_ORG_FAILED = "envkey/GENERATE_DEMO_ORG_FAILED",

  SOCKET_SUBSCRIBE_ORG_CHANNEL = "envkey/SOCKET_SUBSCRIBE_ORG_CHANNEL",
  SOCKET_SUBSCRIBE_OBJECT_CHANNEL = "envkey/SOCKET_SUBSCRIBE_OBJECT_CHANNEL",
  SOCKET_UNSUBSCRIBE_OBJECT_CHANNEL = "envkey/SOCKET_UNSUBSCRIBE_OBJECT_CHANNEL",
  SOCKET_USER_UNSUBSCRIBED_ORG_CHANNEL = "envkey/SOCKET_USER_UNSUBSCRIBED_ORG_CHANNEL",
  SOCKET_USER_UNSUBSCRIBED_OBJECT_CHANNEL = "envkey/SOCKET_USER_UNSUBSCRIBED_OBJECT_CHANNEL",
  SOCKET_USER_SUBSCRIBED_ORG_CHANNEL = "envkey/SOCKET_USER_SUBSCRIBED_ORG_CHANNEL",
  SOCKET_USER_SUBSCRIBED_OBJECT_CHANNEL = "envkey/SOCKET_USER_SUBSCRIBED_OBJECT_CHANNEL",
  SOCKET_UPDATE_ENVS_STATUS = "envkey/SOCKET_UPDATE_ENVS_STATUS",
  PROCESSED_SOCKET_UPDATE_ENVS_STATUS = "envkey/PROCESSED_SOCKET_UPDATE_ENVS_STATUS",
  SOCKET_UPDATE_LOCAL_STATUS = "envkey/SOCKET_UPDATE_LOCAL_STATUS",
  SOCKET_BROADCAST_ENVS_STATUS = "envkey/SOCKET_BROADCAST_ENVS_STATUS",
  SOCKET_UNSUBSCRIBE_ALL = "envkey/SOCKET_UNSUBSCRIBE_ALL",
  SOCKET_ORG_UPDATE = "envkey/SOCKET_ORG_UPDATE",

  BILLING_UPGRADE_SUBSCRIPTION = "envkey/BILLING_UPGRADE_SUBSCRIPTION",
  BILLING_CANCEL_SUBSCRIPTION = "envkey/BILLING_CANCEL_SUBSCRIPTION",
  BILLING_UPDATE_CARD = "envkey/BILLING_UPDATE_CARD",
  BILLING_OPEN_STRIPE_FORM = "envkey/BILLING_OPEN_STRIPE_FORM",
  BILLING_STRIPE_FORM_SUBMITTED = "envkey/BILLING_STRIPE_FORM_SUBMITTED",
  BILLING_STRIPE_FORM_CLOSED = "envkey/BILLING_STRIPE_FORM_CLOSED",
  BILLING_UPDATE_CARD_REQUEST = "envkey/BILLING_UPDATE_CARD_REQUEST",
  BILLING_UPDATE_CARD_SUCCESS = "envkey/BILLING_UPDATE_CARD_SUCCESS",
  BILLING_UPDATE_CARD_FAILED = "envkey/BILLING_UPDATE_CARD_FAILED",
  BILLING_UPDATE_SUBSCRIPTION_REQUEST = "envkey/BILLING_UPDATE_SUBSCRIPTION_REQUEST",
  BILLING_UPDATE_SUBSCRIPTION_SUCCESS = "envkey/BILLING_UPDATE_SUBSCRIPTION_SUCCESS",
  BILLING_UPDATE_SUBSCRIPTION_FAILED = "envkey/BILLING_UPDATE_SUBSCRIPTION_FAILED"

