export const
  LOGIN = "envkey/LOGIN",
  LOGIN_REQUEST = "envkey/LOGIN_REQUEST",
  LOGIN_SUCCESS = "envkey/LOGIN_SUCCESS",
  LOGIN_FAILED = "envkey/LOGIN_FAILED",

  REGISTER = "envkey/REGISTER",
  REGISTER_REQUEST = "envkey/REGISTER_REQUEST",
  REGISTER_SUCCESS = "envkey/REGISTER_SUCCESS",
  REGISTER_FAILED = "envkey/REGISTER_FAILED",

  APP_LOADED = "envkey/APP_LOADED",

  ACCEPT_INVITE = "envkey/ACCEPT_INVITE",
  ACCEPT_INVITE_REQUEST = "envkey/ACCEPT_INVITE_REQUEST",
  ACCEPT_INVITE_SUCCESS = "envkey/ACCEPT_INVITE_SUCCESS",
  ACCEPT_INVITE_FAILED = "envkey/ACCEPT_INVITE_FAILED",

  CREATE_ORG_REQUEST = "envkey/CREATE_ORG_REQUEST",
  CREATE_ORG_SUCCESS = "envkey/CREATE_ORG_SUCCESS",
  CREATE_ORG_FAILED = "envkey/CREATE_ORG_FAILED",

  FETCH_CURRENT_USER_REQUEST = "envkey/FETCH_CURRENT_USER_REQUEST",
  FETCH_CURRENT_USER_SUCCESS = "envkey/FETCH_CURRENT_USER_SUCCESS",
  FETCH_CURRENT_USER_FAILED = "envkey/FETCH_CURRENT_USER_FAILED",

  FETCH_OBJECT_DETAILS_REQUEST = "envkey/FETCH_OBJECT_DETAILS_REQUEST",
  FETCH_OBJECT_DETAILS_SUCCESS = "envkey/FETCH_OBJECT_DETAILS_SUCCESS",
  FETCH_OBJECT_DETAILS_FAILED = "envkey/FETCH_OBJECT_FAILED",

  CREATE_OBJECT_REQUEST = "envkey/CREATE_OBJECT_REQUEST",
  CREATE_OBJECT_SUCCESS = "envkey/CREATE_OBJECT_SUCCESS",
  CREATE_OBJECT_FAILED = "envkey/CREATE_OBJECT_FAILED",

  UPDATE_OBJECT_SETTINGS_REQUEST = "envkey/UPDATE_OBJECT_SETTINGS_REQUEST",
  UPDATE_OBJECT_SETTINGS_SUCCESS = "envkey/UPDATE_OBJECT_SETTINGS_SUCCESS",
  UPDATE_OBJECT_SETTINGS_FAILED = "envkey/UPDATE_OBJECT_SETTINGS_FAILED",

  RENAME_OBJECT_REQUEST = "envkey/RENAME_OBJECT_REQUEST",
  RENAME_OBJECT_SUCCESS = "envkey/RENAME_OBJECT_SUCCESS",
  RENAME_OBJECT_FAILED = "envkey/RENAME_OBJECT_FAILED",

  UPDATE_ENV_REQUEST = "envkey/UPDATE_ENV_REQUEST",
  UPDATE_ENV_SUCCESS = "envkey/UPDATE_ENV_SUCCESS",
  UPDATE_ENV_FAILED = "envkey/UPDATE_ENV_FAILED",

  REMOVE_OBJECT_REQUEST = "envkey/REMOVE_OBJECT_REQUEST",
  REMOVE_OBJECT_SUCCESS = "envkey/REMOVE_OBJECT_SUCCESS",
  REMOVE_OBJECT_FAILED = "envkey/REMOVE_OBJECT_FAILED",

  ADD_ASSOC_REQUEST = "envkey/ADD_ASSOC_REQUEST",
  ADD_ASSOC_SUCCESS = "envkey/ADD_ASSOC_SUCCESS",
  ADD_ASSOC_FAILED = "envkey/ADD_ASSOC_FAILED",

  CREATE_ASSOC_REQUEST = "envkey/CREATE_ASSOC_REQUEST",
  CREATE_ASSOC_SUCCESS = "envkey/CREATE_ASSOC_SUCCESS",
  CREATE_ASSOC_FAILED = "envkey/CREATE_ASSOC_FAILED",

  REMOVE_ASSOC_REQUEST = "envkey/REMOVE_ASSOC_REQUEST",
  REMOVE_ASSOC_SUCCESS = "envkey/REMOVE_ASSOC_SUCCESS",
  REMOVE_ASSOC_FAILED = "envkey/REMOVE_ASSOC_FAILED",

  GENERATE_ASSOC_KEY = "envkey/GENERATE_ASSOC_KEY",
  GENERATE_ASSOC_KEY_REQUEST = "envkey/GENERATE_ASSOC_KEY_REQUEST",
  GENERATE_ASSOC_KEY_SUCCESS = "envkey/GENERATE_ASSOC_KEY_SUCCESS",
  GENERATE_ASSOC_KEY_FAILED = "envkey/GENERATE_ASSOC_KEY_FAILED",

  GENERATE_USER_KEYPAIR = "envkey/GENERATE_USER_KEYPAIR",
  GENERATE_USER_KEYPAIR_SUCCESS = "envkey/GENERATE_USER_KEYPAIR_SUCCESS",

  HASH_USER_PASSWORD = "envkey/HASH_USER_PASSWORD",
  HASH_USER_PASSWORD_SUCCESS = "envkey/HASH_USER_PASSWORD_SUCCESS",

  HASH_PASSWORD_AND_GENERATE_KEYS = "envkey/HASH_PASSWORD_AND_GENERATE_KEYS",
  HASH_PASSWORD_AND_GENERATE_KEYS_SUCCESS = "envkey/HASH_PASSWORD_AND_GENERATE_KEYS_SUCCESS",

  GRANT_ENV_ACCESS = "envkey/GRANT_ENV_ACCESS",
  GRANT_ENV_ACCESS_REQUEST = "envkey/GRANT_ENV_ACCESS_REQUEST",
  GRANT_ENV_ACCESS_SUCCESS = "envkey/GRANT_ENV_ACCESS_SUCCESS",
  GRANT_ENV_ACCESS_FAILED = "envkey/GRANT_ENV_ACCESS_FAILED",

  CHECK_INVITES_ACCEPTED_REQUEST = "envkey/CHECK_INVITES_ACCEPTED_REQUEST",
  CHECK_INVITES_ACCEPTED_SUCCESS = "envkey/CHECK_INVITES_ACCEPTED_SUCCESS",
  CHECK_INVITES_ACCEPTED_FAILED = "envkey/CHECK_INVITES_ACCEPTED_FAILED",

  CHECK_ACCESS_GRANTED_REQUEST = "envkey/CHECK_ACCESS_GRANTED_REQUEST",
  CHECK_ACCESS_GRANTED_SUCCESS = "envkey/CHECK_ACCESS_GRANTED_SUCCESS",
  CHECK_ACCESS_GRANTED_FAILED = "envkey/CHECK_ACCESS_GRANTED_FAILED",

  LOGOUT = "envkey/LOGOUT",

  SELECT_ORG = "envkey/SELECT_ORG",

  TOKEN_INVALID = "envkey/TOKEN_INVALID",
  ORG_INVALID = "envkey/ORG_INVALID",

  CREATE_ENTRY = "envkey/CREATE_ENTRY",
  UPDATE_ENTRY = "envkey/UPDATE_ENTRY",
  REMOVE_ENTRY = "envkey/REMOVE_ENTRY",
  UPDATE_ENTRY_VAL = "envkey/UPDATE_ENTRY_VAL",

  DECRYPT = "envkey/DECRYPT",

  DECRYPT_PRIVKEY = "envkey/DECRYPT_PRIVKEY",
  DECRYPT_PRIVKEY_FAILED = "envkey/DECRYPT_PRIVKEY_FAILED",
  DECRYPT_PRIVKEY_SUCCESS = "envkey/DECRYPT_PRIVKEY_SUCCESS",

  DECRYPT_ENVS = "envkey/DECRYPT_ENVS",
  DECRYPT_ENVS_FAILED = "envkey/DECRYPT_ENVS_FAILED",
  DECRYPT_ENVS_SUCCESS = "envkey/DECRYPT_ENVS_SUCCESS",

  API_SUCCESS = "envkey/API_SUCCESS",
  API_FAILED = "envkey/API_FAILED",

  START_DEMO = "envkey/START_DEMO"

  // SELECTED_OBJECT_ROUTE = "envkey/SELECTED_OBJECT_ROUTE"


