# If you do not have OpenSSL installed, update
# the following line to use 'http://' instead
source 'https://rubygems.org'

# Slim for templates
gem 'slim', '>= 3.0'

# For faster file watcher updates on Windows:
gem 'wdm', '~> 0.1.0', platforms: [:mswin, :mingw]

# windows does not come with time zone data
gem 'tzinfo-data', platforms: [:mswin, :mingw]

# Middleman Gems
gem 'sass'
gem 'middleman-sprockets', '>= 4.0.0.rc.1'
gem 'middleman', '>= 4.0.0.rc.1'
gem 'middleman-livereload'
gem 'sass-globbing'

# Env vars
gem 'dotenv'

# Utilitis
gem "pry"
