// Generated by https://pagedraw.io/pages/5397
import React from 'react';
function render() {
    return <div className="component_1">
        <style>
            { ".component_1 {\n\
                display: flex;\n\
                flex-direction: column;\n\
                flex-grow: 1;\n\
                font-family: Helvetica, Arial, sans-serif;\n\
                font-weight: 400;\n\
                font-style: normal;\n\
                color: rgb(68, 68, 68);\n\
                text-decoration: none;\n\
                word-wrap: break-word;\n\
                font-size: 14px;\n\
                line-height: normal;\n\
                letter-spacing: 0px;\n\
                text-align: left;\n\
            }\n\
            \n\
            .component_1-0 {\n\
                display: flex;\n\
                flex-grow: 1;\n\
                flex-basis: 0px;\n\
                min-height: fit-content;\n\
            }\n\
            \n\
            .component_1-component_1 {\n\
                display: flex;\n\
                flex-direction: column;\n\
                flex-grow: 1;\n\
                flex-basis: 0px;\n\
                min-height: fit-content;\n\
            }\n\
            \n\
            .component_1-0-0-0 {\n\
                display: flex;\n\
                padding-right: 1px;\n\
            }\n\
            \n\
            .component_1-path-6 {\n\
                display: flex;\n\
                flex-direction: column;\n\
                padding-top: 17px;\n\
                padding-bottom: 16px;\n\
                background: rgb(255, 255, 255);\n\
            }\n\
            \n\
            .component_1-0-0-0-0-0 {\n\
                display: flex;\n\
                padding-left: 13px;\n\
                padding-right: 15px;\n\
            }\n\
            \n\
            .component_1-0-0-0-0-0-0 {\n\
                display: flex;\n\
                flex-direction: column;\n\
                padding-top: 4px;\n\
                padding-bottom: 3px;\n\
            }\n\
            \n\
            .component_1-0-0-0-0-0-0-0 {\n\
                display: flex;\n\
            }\n\
            \n\
            .component_1-dane_schneider_gmail-8 {\n\
                width: 180px;\n\
                flex-shrink: 0;\n\
            }\n\
            \n\
            .component_1-path-1 {\n\
                display: flex;\n\
                flex-direction: column;\n\
                margin-left: 62px;\n\
                padding-top: 5px;\n\
                padding-bottom: 5px;\n\
                border-radius: 2px;\n\
                background: rgb(31, 127, 162);\n\
                color: rgb(255, 255, 255);\n\
                font-size: 11px;\n\
            }\n\
            \n\
            .component_1-0-0-0-0-0-1-0 {\n\
                display: flex;\n\
                padding-left: 12px;\n\
                padding-right: 10px;\n\
            }\n\
            \n\
            .component_1-select-1 {\n\
                width: 44px;\n\
                flex-shrink: 0;\n\
            }\n\
            \n\
            .component_1-0-0-1 {\n\
                display: flex;\n\
                margin-top: 25px;\n\
                padding-left: 1px;\n\
            }\n\
            \n\
            .component_1-path-12 {\n\
                display: flex;\n\
                flex-direction: column;\n\
                padding-top: 15px;\n\
                padding-bottom: 18px;\n\
                background: rgb(255, 255, 255);\n\
            }\n\
            \n\
            .component_1-0-0-1-0-0 {\n\
                display: flex;\n\
                padding-left: 15px;\n\
                padding-right: 13px;\n\
            }\n\
            \n\
            .component_1-0-0-1-0-0-0 {\n\
                display: flex;\n\
                flex-direction: column;\n\
                padding-top: 4px;\n\
                padding-bottom: 3px;\n\
            }\n\
            \n\
            .component_1-0-0-1-0-0-0-0 {\n\
                display: flex;\n\
            }\n\
            \n\
            .component_1-add_an_account-4 {\n\
                width: 110px;\n\
                flex-shrink: 0;\n\
            }\n\
            \n\
            .component_1-path-8 {\n\
                display: flex;\n\
                flex-direction: column;\n\
                margin-left: 132px;\n\
                padding-top: 5px;\n\
                padding-bottom: 5px;\n\
                border-radius: 2px;\n\
                background: rgb(253, 160, 43);\n\
                color: rgb(255, 255, 255);\n\
                font-size: 11px;\n\
            }\n\
            \n\
            .component_1-0-0-1-0-0-1-0 {\n\
                display: flex;\n\
                padding-left: 19px;\n\
                padding-right: 15px;\n\
            }\n\
            \n\
            .component_1-add-1 {\n\
                width: 32px;\n\
                flex-shrink: 0;\n\
            }\n\
            \n\
            .component_1-0-0-2 {\n\
                flex-grow: 1;\n\
                flex-basis: 0px;\n\
            }\n\
            \n\
            * {\n\
                box-sizing: border-box;\n\
            }\n\
            \n\
            body {\n\
                margin: 0;\n\
            }\n\
            \n\
            button:hover {\n\
                cursor: pointer;\n\
            }\n\
            \n\
            a {\n\
                text-decoration: none;\n\
                color: inherit;\n\
            }\n\
            \n\
            .pd-onhover-parent >.pd-onhover {\n\
                display: none;\n\
            }\n\
            \n\
            .pd-onhover-parent:hover > * {\n\
                display: none;\n\
            }\n\
            \n\
            .pd-onhover-parent:hover > .pd-onhover {\n\
                display: flex;\n\
            }\n\
            \n\
            .pd-onactive-parent > .pd-onactive {\n\
                display: none;\n\
            }\n\
            \n\
            .pd-onactive-parent:active > * {\n\
                display: none;\n\
            }\n\
            \n\
            .pd-onactive-parent:active > .pd-onactive {\n\
                display: flex;\n\
            }\n\
            \n\
            .pd-onactive-parent.pd-onhover-parent:active > .pd-onhover {\n\
                display: none;\n\
            }" }
        </style>
        <div className="component_1-0">
            <div className="component_1-component_1">
                <div className="component_1-0-0-0">
                    <div className="component_1-path-6">
                        <div className="component_1-0-0-0-0-0">
                            <div className="component_1-0-0-0-0-0-0">
                                <div className="component_1-0-0-0-0-0-0-0">
                                    <div className="component_1-dane_schneider_gmail-8">
                                        dane.schneider@gmail.com
                                    </div>
                                </div>
                            </div>
                            <div className="component_1-path-1">
                                <div className="component_1-0-0-0-0-0-1-0">
                                    <div className="component_1-select-1">SELECT</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div className="component_1-0-0-1">
                    <div className="component_1-path-12">
                        <div className="component_1-0-0-1-0-0">
                            <div className="component_1-0-0-1-0-0-0">
                                <div className="component_1-0-0-1-0-0-0-0">
                                    <div className="component_1-add_an_account-4">
                                        Add An Account
                                    </div>
                                </div>
                            </div>
                            <div className="component_1-path-8">
                                <div className="component_1-0-0-1-0-0-1-0">
                                    <div className="component_1-add-1">ADD</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div className="component_1-0-0-2" />
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}